#!/usr/bin/env python3
"""Generate docs/models.md — the model and language reference.

The WebUI already answers "what does this model speak?" on each card. This
covers the other direction and the offline case: choosing a model before
installing anything, and looking up which models cover a given language.

Everything here is derived from app/catalog.py, so the document cannot drift
from the catalog it describes. `--check` verifies the committed file is current
without writing, which is what CI runs.

Underscored module name (unlike harvest-model-pins.py) so the test suite can
run this file directly as a subprocess with a stable path.

Usage:
    uv run scripts/generate_model_docs.py
    uv run scripts/generate_model_docs.py --check
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.catalog import (  # noqa: E402
    DEFAULT_CATALOG,
    LANGUAGE_NAMES,
    CatalogModel,
    language_names,
)

DOCS_PATH = Path(__file__).resolve().parent.parent / "docs" / "models.md"

# Above this, naming every language in a table cell makes the row unreadable;
# the full list still appears in the per-language index below.
INLINE_LANGUAGE_LIMIT = 6

ENGINE_ORDER = (
    "sherpa-onnx",
    "faster-whisper",
    "moonshine",
    "whisper.cpp",
    "whisperkit",
    "mlx-audio",
)

ENGINE_NOTES = {
    "sherpa-onnx": "Portable INT8 CPU models. Run everywhere, including containers.",
    "faster-whisper": "CTranslate2 Whisper. Kept resident; the broad multilingual fallback.",
    "moonshine": "Compact dictation models. English tiers support live streaming.",
    "whisper.cpp": "GGML models through the standalone `whisper-cli` binary.",
    "whisperkit": "Core ML, **macOS only**. Hidden on Linux and in containers.",
    "mlx-audio": "MLX, **Apple silicon only**. Hidden on Linux and in containers.",
}


def format_size(size_bytes: int) -> str:
    if size_bytes >= 1_000_000_000:
        return f"{size_bytes / 1_000_000_000:.2f} GB"
    return f"{size_bytes / 1_000_000:.0f} MB"


def language_cell(model: CatalogModel) -> str:
    """Name the languages when the list is short, otherwise link the shared set.

    Long lists are pooled: 18 of the 25 multi-language models carry the exact
    same 100-language Whisper set, so spelling it out per row would add ~1800
    repeated names and bury the table.
    """
    names = language_names(model.language_codes)
    if not names:
        return "_unknown_"
    if len(names) <= INLINE_LANGUAGE_LIMIT:
        return ", ".join(names)
    return f"[{len(names)} languages](#{set_anchor(model.language_codes)})"


def set_anchor(codes: tuple[str, ...]) -> str:
    return f"language-set-{len(codes)}"


def model_flags(model: CatalogModel) -> str:
    flags = []
    if model.supports_streaming:
        flags.append("streaming")
    if model.detects_language_automatically:
        flags.append("auto language")
    if model.apple_silicon_only:
        flags.append("Apple silicon")
    if not model.commercial_use:
        flags.append("personal use")
    return ", ".join(flags) or "—"


def render() -> str:
    lines: list[str] = []
    add = lines.append

    add("<!-- Generated by scripts/generate_model_docs.py. Do not edit by hand. -->")
    add("")
    add("# Models and languages")
    add("")
    add(
        f"Every model in the catalog ({len(DEFAULT_CATALOG)} of them), what it speaks, and "
        "which models cover a given language. Generated from `app/catalog.py`, so it "
        "always matches the catalog the gateway actually ships."
    )
    add("")
    add(
        "The WebUI Models tab shows the same information per card, with a language "
        "filter. Use this page to pick a model before installing anything."
    )
    add("")
    add("- [Models by engine](#models-by-engine)")
    add("- [Language sets](#language-sets)")
    add("- [Language index](#language-index)")
    add("")
    add("## Reading the flags")
    add("")
    add("| Flag | Meaning |")
    add("| --- | --- |")
    add("| `streaming` | Decodes incrementally over a WebSocket while you speak |")
    add(
        "| `auto language` | The model picks the language itself. The language chosen "
        "in the app **cannot** constrain it, so the listed languages are what it "
        "handles well, not options you select |"
    )
    add("| `Apple silicon` | Needs an arm64 Mac; hidden on Linux and in containers |")
    add("| `personal use` | Licence restricts commercial use — check before deploying |")
    add("")
    add("## Models by engine")
    add("")

    by_engine: dict[str, list[CatalogModel]] = defaultdict(list)
    for model in DEFAULT_CATALOG:
        by_engine[model.engine].append(model)

    for engine in [*ENGINE_ORDER, *sorted(set(by_engine) - set(ENGINE_ORDER))]:
        models = by_engine.get(engine)
        if not models:
            continue
        add(f"### {engine}")
        add("")
        note = ENGINE_NOTES.get(engine)
        if note:
            add(note)
            add("")
        add("| Model | Download | Languages | Flags | Licence |")
        add("| --- | ---: | --- | --- | --- |")
        for model in models:
            add(
                f"| {model.label} | {format_size(model.size_bytes)} "
                f"| {language_cell(model)} | {model_flags(model)} | {model.license_name} |"
            )
        add("")

    add("## Language sets")
    add("")
    shared: dict[tuple[str, ...], list[CatalogModel]] = defaultdict(list)
    for model in DEFAULT_CATALOG:
        if len(model.language_codes) > INLINE_LANGUAGE_LIMIT:
            shared[model.language_codes].append(model)
    add(
        "The tables above link here rather than repeating long lists. Each set below "
        "is shared verbatim by every model listed with it."
    )
    add("")
    for codes in sorted(shared, key=len):
        models = shared[codes]
        add(f'<a id="{set_anchor(codes)}"></a>')
        add("")
        add(f"### {len(codes)} languages")
        add("")
        add("Used by: " + ", ".join(sorted(m.label for m in models)) + ".")
        add("")
        add(", ".join(language_names(codes)) + ".")
        add("")

    add("## Language index")
    add("")
    covered: dict[str, list[CatalogModel]] = defaultdict(list)
    for model in DEFAULT_CATALOG:
        for code in model.language_codes:
            covered[code].append(model)
    add(
        f"{len(covered)} languages, alphabetically. Expand one to see every model that "
        "covers it. A model marked `auto language` will not let you pin this language "
        "explicitly — it decides for itself."
    )
    add("")

    for code in sorted(covered, key=lambda c: (LANGUAGE_NAMES.get(c, c).lower(), c)):
        models = covered[code]
        name = LANGUAGE_NAMES.get(code, code)
        add("<details>")
        add(
            f"<summary><strong>{name}</strong> (<code>{code}</code>) — {len(models)} models"
            "</summary>"
        )
        add("")
        add("| Model | Engine | Download | Flags |")
        add("| --- | --- | ---: | --- |")
        for model in sorted(models, key=lambda m: (m.engine, m.size_bytes)):
            add(
                f"| {model.label} | {model.engine} | {format_size(model.size_bytes)} "
                f"| {model_flags(model)} |"
            )
        add("")
        add("</details>")
        add("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed file is out of date instead of rewriting it.",
    )
    parser.add_argument("--output", type=Path, default=DOCS_PATH)
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
        if current != rendered:
            print(
                f"{args.output} is out of date. Run: uv run scripts/generate_model_docs.py",
                file=sys.stderr,
            )
            return 1
        print(f"{args.output} is up to date")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(
        f"Wrote {args.output} — {len(DEFAULT_CATALOG)} models, {len(rendered.splitlines())} lines"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
